repetitions: 1
num_rngs: 5
simulate_until: 4000000
topology_file: "topology.yaml"
output_dir: "out"
engine: "simpy"
time_unit: "us"

metrics:
  - name: "queuing_time"
    type: ["vector", "mean", "percentiles"]
  - name: "throughput"
    type: ["vector"]
  - name: "congestion_window"
    type: ["vector"]
  - name: "latency"
    type: ["vector"]
  - name: "queue_size"
    type: ["vector"]

max_processes: 8
log_level: "debug"


# The following parameters are accessible to all modules in the simulation
global_params:
  aqm_params:
    R_plus: 0.001
    C: 100000
    N_minus: 1
    q_ref: 20
  flow_descriptors:
    - flow_id: 0
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.4
        - 0.4
        - 0.4
        - 0.4
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 1
      flow_type: "default"
      source: "qn3"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.4
        - 0.4
        - 0.4
      path:
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 2
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.4
        - 0.4
        - 0.4
        - 0.4
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 3
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.3
        - 0.3
        - 0.3
        - 0.3
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
