repetitions: 1
num_rngs: 50
simulate_until: 24000000
topology_file: "topology.yaml"
output_dir: "out"
engine: "simpy"
time_unit: "us"

metrics:
  - name: "queuing_time"
    type: ["vector", "mean", "percentiles"]
  - name: "throughput"
    type: ["vector"]
  - name: "IRG"
    type: ["vector"]
  - name: "latency"
    type: ["vector"]
  - name: "queue_size"
    type: ["vector"]
  - name: "queue_size_free"
    type: [ "vector" ]
  - name: "fidelity"
    type: ["vector"]

max_processes: 8
log_level: "debug"


# The following parameters are accessible to all modules in the simulation
global_params:
  aqm_params:
    R_plus: 0.05
    C: 4000
    N_minus: 4
    q_ref: 5
  flow_descriptors:
    - flow_id: 0
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 1
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 2
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 3
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 4
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 5
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 6
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 7
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 8
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 9
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 10
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 11
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 12
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 13
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 14
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 15
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 16
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 17
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 18
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 19
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 20
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 21
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 22
      flow_type: "default"
      source: "qn0"
      destination: "qn4"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn0"
        - "lc0"
        - "qn1"
        - "lc1"
        - "qn2"
        - "lc2"
        - "qn3"
        - "lc3"
        - "qn4"
      direction: "upstream"  # useful for nodes to infer the output port of messages (no routing for now)
    - flow_id: 23
      flow_type: "default"
      source: "qn4"
      destination: "qn0"
      flow_priority: 0
      success_probs: # success probability of LLE attempts on each link, due to pump power
        - 0.04
        - 0.04
        - 0.04
        - 0.04
      path:
        - "qn4"
        - "lc3"
        - "qn3"
        - "lc2"
        - "qn2"
        - "lc1"
        - "qn1"
        - "lc0"
        - "qn0"
      direction: "downstream"  # useful for nodes to infer the output port of messages (no routing for now)