repetitions: 1
num_rngs: 15
simulate_until: 48000000
topology_file: "topology.yaml"
output_dir: "out"
engine: "simpy"
time_unit: "us"

metrics:
  - name: "features"
    type: ["vector"]

max_processes: 8
log_level: "debug"


# The following parameters are accessible to all modules in the simulation
global_params:
  storage_qbits: 50
  avg_request_interarrival_time: 150
  lleg_prob: 0.1
  lleg_attempt_period: 10 # us
  distance_vectors:
    - node: "qn0"
      distance_vector:
        - node: "qn1"
          distance: 1
          port: "q0"
        - node: "qn3"
          distance: 1
          port: "q1"
        - node: "qn4"
          distance: 2
        - node: "qn4"
          distance: 2
        - node: "qn5"
          distance: 3
    - node: "qn1"
      distance_vector:
        - node: "qn0"
          distance: 1
          port: "q0"
        - node: "qn2"
          distance: 1
          port: "q1"
        - node: "qn3"
          distance: 2
        - node: "qn4"
          distance: 1
          port: "q2"
        - node: "qn5"
          distance: 2
    - node: "qn2"
      distance_vector:
        - node: "qn0"
          distance: 2
        - node: "qn1"
          distance: 1
          port: "q0"
        - node: "qn3"
          distance: 2
        - node: "qn4"
          distance: 2
        - node: "qn5"
          distance: 1
          port: "q1"
    - node: "qn3"
      distance_vector:
        - node: "qn0"
          distance: 1
          port: "q0"
        - node: "qn1"
          distance: 2
        - node: "qn2"
          distance: 2
        - node: "qn4"
          distance: 1
          port: "q1"
        - node: "qn5"
          distance: 2
    - node: "qn4"
      distance_vector:
        - node: "qn0"
          distance: 2
        - node: "qn1"
          distance: 1
          port: "q0"
        - node: "qn2"
          distance: 2
        - node: "qn3"
          distance: 1
          port: "q1"
        - node: "qn5"
          distance: 1
          port: "q2"
    - node: "qn5"
      distance_vector:
        - node: "qn0"
          distance: 3
        - node: "qn1"
          distance: 2
        - node: "qn2"
          distance: 1
          port: "q0"
        - node: "qn3"
          distance: 2
        - node: "qn4"
          distance: 1
          port: "q1"

  routing_tables:
    - node: "qn0"
      routing_table:
        - port: 0
          dest: "default"
        - port: 1
          dest:
            - "qn3"
            - "qn4"
    - node: "qn1"
      routing_table:
        - port: 1
          dest: "default"
        - port: 0
          dest:
            - "qn0"
            - "qn3"
        - port: 2
          dest:
            - "qn4"
    - node: "qn2"
      routing_table:
        - port: 0
          dest:
            - "qn1"
            - "qn3"
        - port: 1
          dest: "default"
    - node: "qn3"
      routing_table:
        - port: 1
          dest: "default"
        - port: 0
          dest:
            - "qn0"
            - "qn1"
    - node: "qn4"
      routing_table:
        - port: 0
          dest:
            - "qn0"
            - "qn3"
        - port: 1
          dest: "default"
        - port: 2
          dest:
              - "qn1"
    - node: "qn5"
      routing_table:
        - port: 0
          dest: "default"
        - port: 1
          dest:
              - "qn3"
              - "qn4"