repetitions: 1
num_rngs: 2
simulate_until: 800
topology_file: "qnum_initial_topology.yaml"
output_dir: "out"
engine: "simpy"
time_unit: "us"

metrics:
  - name: "Fidelity"
    type: ["vector", "mean", "percentiles"]

max_processes: 8
log_level: "info"
