repetitions: 1
num_rngs: 1
simulate_until: 8000
yaml_directory: "./"
engine: "simpy"
time_unit: "s"

metrics:
  - name: "Throughput"
    type: ["vector", "mean", "percentiles"]

max_processes: 8
log_level: "info"
