repetitions: 1
num_rngs: 5
simulate_until: 20000
topology_file: "topology.yaml"
output_dir: "out"
engine: "simpy"
time_unit: "us"

metrics:
  - name: "queuing_time"
    type: ["vector", "mean", "percentiles"]
  - name: "throughput"
    type: ["vector"]
  - name: "congestion_window"
    type: ["vector"]
  - name: "latency"
    type: ["vector"]

max_processes: 8
log_level: "debug"
